---
- name: Deploy Hicam
  hosts: hicam

  tasks:
  - name: Copy docker-compose file to remote
    become: true
    ansible.builtin.copy:
      src: /Users/web.varlamov/IdeaProjects/hicam/production/docker-compose/docker-compose.yaml
      dest: /home/webvarlamov/docker-compose.yaml

  - name: Copy coturn config file to remote
    become: true
    ansible.builtin.copy:
      src: /Users/web.varlamov/IdeaProjects/hicam/production/coturn/turnserver.conf
      dest: /home/webvarlamov/turnserver.conf

  - name: Auth to Cloud Registry
    become: true
    ansible.builtin.raw: curl -H Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | cut -f1 -d',' | cut -f2 -d':' | tr -d '"' | docker login --username iam --password-stdin cr.yandex

  - name: Docker compose up
    become: true
    ansible.builtin.raw: docker-compose --file /home/webvarlamov/docker-compose.yaml down

  - name: Docker compose up
    become: true
    ansible.builtin.raw: docker-compose --file /home/webvarlamov/docker-compose.yaml up -d




