---
- name: Docker install
  hosts: hicam

  tasks:
  - name: Install required system packages
    become: true
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common' ]

  - name: Add Docker GPG apt Key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repositor
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    become: true
    apt: update_cache=yes name=docker-ce state=latest

  - name: Run and enable docker
    become: true
    service:
      name: docker
      state: started
      enabled: true

  - name: Add "webvarlamov" user to "docker" group
    become: true
    user:
      name: "webvarlamov"
      group: "docker"
      append: yes
    tags:
      - docker

  - name: Install Python
    become: true
    apt: name={{ item }} state=latest update_cache=yes
    loop: ['python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Install Docker Module for Python
    become: true
    pip:
      name: docker

  - name: Install docker-compose
    become: true
    get_url:
      url : "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64"
      dest: /usr/local/bin/docker-compose

  - name: Changing permission
    become: true
    ansible.builtin.file:
      path: /usr/local/bin/docker-compose
      mode: 777

  - name: Reboot the machine
    become: true
    ansible.builtin.reboot:

